// Generated by CoffeeScript 1.10.0
(function() {
  define('Text', ['App'], function(app) {
    var Text;
    return Text = (function() {
      function Text(id, position, text) {
        this.id = id;
        this.text = text;
        this.x = position.x;
        this.y = position.y;
      }

      Text.prototype.draw = function() {
        app.ctx.fillStyle = 'black';
        app.ctx.fillText(this.text(), this.x, this.y + 8);
      };

      return Text;

    })();
  });

}).call(this);
