define 'Colors', [], () ->
  Colors =
    BUTTONACTIVE: '#948661'
    BUTTONINACTIVE: '#ddd'
    BUTTONNOTALLOWED: 'grey'
    BUTTONDISABLED: 'grey'
    BUTTONNORMALTEXTCOLOR: 'black'
    BUTTONNORMALDISABLEDTEXTCOLOR: '#444'
    BUTTONMENUINACTIVE: 'white'

    BCKISLANDMAP: '#ddd'
    CULTSERAPIS: '#377eb8'
    CULTISIS: '#4daf4a'
    CULTANUBIS: '#a65628'
    CULTBASTET: '#e41a1c'

    FOODINDICATORSUPER: '#1a9641'
    FOODINDICATORGOOD: '#a6d96a'
    FOODINDICATORBAD: '#fdae61'
    FOODINDICATORCRITICAL: '#d7191c'

    GOLD: '#F58706'
    PORTMAP: '#8C1C1C'
    ROUTEMAP: '#261501'
    SAND: '#F58706'
    STORMMAP: '#578885'
