// Generated by CoffeeScript 1.10.0
(function() {
  define('Collection', ['Base'], function(Base) {
    var Collection;
    return Collection = (function() {
      function Collection(data) {
        this.data = data;
        this.geometries = [];
      }

      Collection.prototype.addGeometry = function(geometry) {
        geometry.id = this.geometries.length;
        this.geometries.push(geometry);
      };

      Collection.prototype.draw = function() {
        _.each(this.geometries, function(geometry, g) {
          if (geometry) {
            return geometry.draw();
          }
        });
      };

      Collection.prototype.unregisterGeometry = function(id) {
        var spliceIndex;
        spliceIndex = false;
        _.each(this.geometries, (function(_this) {
          return function(geometry, g) {
            if (geometry.id === id) {
              return spliceIndex = g;
            }
          };
        })(this));
        if (spliceIndex !== false) {
          this.geometries.splice(spliceIndex, 1);
        }
      };

      return Collection;

    })();
  });

}).call(this);
