// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define('Islands', ['Base', 'Collection', 'Island'], function(Base, Collection, Island) {
    var Islands;
    return Islands = (function(superClass) {
      extend(Islands, superClass);

      function Islands(data) {
        this.name = 'islands';
        Islands.__super__.constructor.call(this, data);
        return;
      }

      Islands.prototype.registerGeometries = function() {
        _.each(this.data, (function(_this) {
          return function(island, i) {
            var coords;
            coords = [];
            _.each(island.coordinates[0], function(coord, c) {
              return coords.push(app.coordinateToMap({
                lon: coord[0],
                lat: coord[1]
              }));
            });
            return _this.addGeometry(new Island(coords, island));
          };
        })(this));
      };

      return Islands;

    })(Collection);
  });

}).call(this);
