// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define('Rectangle', ['Geometry'], function(Geometry) {
    var Rectangle;
    return Rectangle = (function(superClass) {
      extend(Rectangle, superClass);

      function Rectangle(x, y, h, w, props, color) {
        Rectangle.__super__.constructor.call(this, x, y, h, w, props);
        this.color = '#666';
        this.changeColor(color);
      }

      Rectangle.prototype.draw = function() {
        return Rectangle.__super__.draw.apply(this, arguments);
      };

      Rectangle.prototype.sprite = 'rectangle';

      return Rectangle;

    })(Geometry);
  });

}).call(this);
