// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define('Geography', ['Geometry'], function(Geometry) {
    var Geography;
    return Geography = (function(superClass) {
      extend(Geography, superClass);

      function Geography() {
        return;
      }

      Geography.prototype.getCoords = function() {
        this.viewCoords = this.calculateCoords();
      };

      return Geography;

    })(Geometry);
  });

}).call(this);
