// Generated by CoffeeScript 1.10.0
(function() {
  define('Cursor', ['App', 'Base'], function(app, Base) {
    var Cursor;
    return Cursor = (function() {
      function Cursor() {}

      Cursor.prototype.getPosition = function() {
        return {
          x: (this.x - app.state.position.x) * app.state.zoom,
          y: (this.y - app.state.position.y) * app.state.zoom
        };
      };

      Cursor.prototype.draw = function() {
        var mp;
        mp = app.state.controls.mousePosition;
        app.ctx.beginPath();
        app.ctx.moveTo(mp.x, mp.y);
        app.ctx.lineTo(mp.x, mp.y + 10);
        app.ctx.lineTo(mp.x + 3, mp.y + 7);
        app.ctx.lineTo(mp.x + 8, mp.y + 12);
        app.ctx.lineTo(mp.x + 9, mp.y + 11);
        app.ctx.lineTo(mp.x + 4, mp.y + 6);
        app.ctx.lineTo(mp.x + 8, mp.y + 3);
        app.ctx.closePath();
        app.ctx.fillStyle = 'black';
        return app.ctx.fill();
      };

      return Cursor;

    })();
  });

}).call(this);
