// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define('Route', ['App', 'Geography', 'Base'], function(app, Geography, Base) {
    var Route;
    return Route = (function(superClass) {
      extend(Route, superClass);

      function Route(from, to) {
        this.from = from;
        this.to = to;
        this.speed = 5;
        Route.__super__.constructor.call(this);
        return;
      }

      Route.prototype.draw = function() {
        var fromView, toView;
        fromView = app.coordinateToView(this.from);
        toView = app.coordinateToView(this.to);
        app.ctx.strokeStyle = 'black';
        app.ctx.lineWidth = 1;
        app.ctx.beginPath();
        app.ctx.moveTo(fromView.x, fromView.y);
        app.ctx.lineTo(toView.x, toView.y);
        app.ctx.stroke();
      };

      return Route;

    })(Geography);
  });

}).call(this);
